# Generated by Django 3.0.7 on 2020-09-03 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.CharField(max_length=150)),
                ('excerpt', models.CharField(max_length=255)),
                ('availibility', models.CharField(choices=[('0', 'In Stock'), ('1', 'Out Of Stock'), ('2', 'Comming Soon')], max_length=20)),
                ('price', models.FloatField()),
                ('color', models.CharField(blank=True, max_length=150, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_products', to='ecom.Category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcat_products', to='ecom.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': '3.Product',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='ecom.Product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': '4. Product Images',
            },
        ),
    ]
