# Generated by Django 3.0.7 on 2020-09-03 18:10

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat_products', to='ecom.SubCategory'),
        ),
    ]
