# Generated by Django 3.0.7 on 2020-09-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_leadsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': '3.Brand',
            },
        ),
        migrations.AlterModelOptions(
            name='leadsection',
            options={'verbose_name_plural': '4.Lead Sections'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': '5. Product Images'},
        ),
    ]
