# Generated by Django 3.0.7 on 2020-09-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20200906_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ManyToManyField(blank=True, related_name='brand_products', to='ecom.Brand'),
        ),
    ]
