# Generated by Django 3.0.7 on 2020-09-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0012_compareproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(default='6 month', max_length=150),
            preserve_default=False,
        ),
    ]
