# Generated by Django 3.0.7 on 2020-09-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0015_productreview_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
