# Generated by Django 3.0.7 on 2020-10-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_siteinfo_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subject', models.CharField(max_length=150)),
                ('problem', models.TextField()),
                ('phone_number', models.CharField(max_length=50)),
                ('solved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': '2.Contact Us',
            },
        ),
    ]
