# Generated by Django 3.0.7 on 2020-10-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='banner')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': '3.Banner',
            },
        ),
    ]
