# Generated by Django 3.0.7 on 2020-10-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
