# Generated by Django 3.0.7 on 2020-10-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_banner_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='about_us')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': '4.About Us',
            },
        ),
    ]
