# Generated by Django 3.0.7 on 2020-10-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_sitead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitead',
            options={'verbose_name': 'Site Ad', 'verbose_name_plural': '5.Site Ad'},
        ),
    ]
