# Generated by Django 3.0.7 on 2020-10-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201016_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_option',
            field=models.CharField(default='2', max_length=10),
        ),
    ]
