# Generated by Django 3.0.7 on 2020-10-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_payment_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('1', 'Direct Bank Tranfer'), ('2', 'Cash On Delivery')], default='2', max_length=10),
        ),
    ]
